apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']         
      - job_name: 'cozinha-produtor'
        static_configs:
          - targets: ['cozinha-produtor:8080']
      - job_name: 'pedido-produtor'
        static_configs:
          - targets: ['pedido-produtor:8080']
      - job_name: 'produto-produtor'
        static_configs:
          - targets: ['produto-produtor:8080']
      - job_name: 'usuario-produtor'
        static_configs:
          - targets: ['usuario-produtor:8080']
      - job_name: 'usuario-autenticacao'
        static_configs:
          - targets: ['usuario-autenticacao:8080']