apiVersion: v1
kind: Service
metadata:
  name: usuario-produtor
spec:
  type: NodePort
  selector:
    app: usuario-produtor
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
---
apiVersion: v1
kind: Service
metadata:
  name: usuario-autenticacao
spec:
  type: NodePort
  selector:
    app: usuario-autenticacao
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082